# fly.toml app configuration file generated for game-engine-holy-wildflower-6492 on 2025-11-26T04:37:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'game-engine-holy-wildflower-6492'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  RUST_LOG = 'info'
  SERVER_ADDR = '0.0.0.0:9001'

[[services]]
  protocol = 'tcp'
  internal_port = 80

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[services]]
  protocol = 'tcp'
  internal_port = 9001

  [[services.ports]]
    port = 9001
    handlers = ['tls', 'http']
    force_https = false

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
